name: Build and Upload Spring Boot Artifact

# Trigger the workflow on push or pull request events to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up JDK 17 (you can change the version if needed)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt' # You can also use 'temurin', 'zulu', etc.
          java-version: '17'
          cache: maven

      # Step 3: Cache Maven dependencies
      # This step is optional because setup-java with cache option handles it
      # Included here for clarity
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Build the project with Maven
      - name: Build with Maven
        run: mvn clean package --no-progress --batch-mode

      # Step 5: Upload the built artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: springboot-app
          path: target/*.jar
