name: Packer Status Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  packer-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Packer
        run: |
          sudo apt-get update
          sudo apt-get install -y packer

      - name: Run Packer init
        working-directory: packer
        run: packer init .

      - name: Run Packer Format Check
        working-directory: packer
        run: packer fmt -check -diff .

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build and Test with Maven
        run: mvn clean install

      - name: Prepare Artifact
        run: |
          mkdir -p artifact
          cp target/*.jar artifact/webapp.jar

      - name: Packer validate
        run: |
          cd packer
          packer validate \
            -var "artifact_path=../artifact/webapp.jar" \
            -var "instance_type=t2.micro" \
            -var "region=${{ secrets.AWS_REGION }}" \
            packer-template.pkr.hcl
