name: Packer Status Check

on:
  pull_request:
    paths:
      - 'packer/**/*.pkr.hcl'
  workflow_dispatch:

jobs:
  packer-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Packer
        run: |
          sudo apt-get update
          sudo apt-get install -y packer

      - name: Run Packer init
        working-directory: packer
        run: packer init .

      - name: Run Packer Format Check
        working-directory: packer
        run: packer fmt -check -diff .

      - name: Run Packer Validate
        working-directory: packer
        run: |
          packer validate \
            -var "artifact_path=dummy.jar" \
            -var "db_name=dummy_db" \
            -var "db_username=dummy_user" \
            -var "db_password=dummy_password" \
            -var "instance_type=t2.micro" \
            -var "region=us-east-1" \
            .
