name: Packer Status Check

on:
  pull_request:
    paths:
      - 'packer/**/*.pkr.hcl'
  workflow_dispatch:

jobs:
  packer-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Packer
        working-directory: packer
        run: |
          sudo apt-get update
          sudo apt-get install -y packer


      - name: Run Packer Format Check
        working-directory: packer
        run: packer fmt -check -diff .

      - name: Run Packer Validate
        working-directory: packer
        run: packer validate .
