name: Packer AMI Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-ami:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Application
        run: mvn clean package

      - name: Run Integration Tests
        run: mvn verify

      - name: Prepare Artifact
        run: |
          mkdir -p artifact
          cp target/*.jar artifact/webapp.jar

      - name: Install Packer
        uses: hashicorp/setup-packer@v2
        with:
          packer_version: 'latest'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Packer Build
        run: |
          cd packer
          packer init .
          packer build \
            -var "artifact_path=../artifact/webapp.jar" \
            -var "db_name=${{ secrets.DB_NAME }}" \
            -var "db_username=${{ secrets.DB_USERNAME }}" \
            -var "db_password=${{ secrets.DB_PASSWORD }}" \
            -var "instance_type=t2.micro" \
            -var "region=${{ secrets.AWS_REGION }}" \
            packer-template.pkr.hcl
