name: Packer AMI Build and Share

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-share-ami:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Application
        run: mvn clean package

      - name: Run Integration Tests
        run: mvn verify

      - name: Prepare Artifact
        run: |
          mkdir -p artifact
          cp target/*.jar artifact/webapp.jar

      - name: Install Packer
        uses: hashicorp/setup-packer@v2
        with:
          version: '1.11.2'  # Specify the desired Packer version

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Initialize Packer
        working-directory: packer
        run: packer init packer-template.pkr.hcl

      - name: Validate Packer Template
        working-directory: packer
        run: packer validate -var-file=variables.pkrvars.hcl packer-template.pkr.hcl

      - name: Build AMI
        working-directory: packer
        run: packer build -var-file=variables.pkrvars.hcl packer-template.pkr.hcl

      - name: Extract AMI ID
        working-directory: packer
        id: extract_ami
        run: |
          # Extract the AMI ID without the source prefix
          AMI_ID=$(jq -r '.builds[0].artifact_id' packer/manifest.json | cut -d':' -f2)
          echo "AMI_ID=${AMI_ID}" >> $GITHUB_ENV

      - name: Share AMI with Demo Account
        working-directory: packer
        run: |
          DEMO_ACCOUNT_ID="503561445917"  
          aws ec2 modify-image-attribute \
            --image-id $AMI_ID \
            --launch-permission "Add=[{UserId=${DEMO_ACCOUNT_ID}}]"
